name: "Code Linters"

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main", "wip/**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-fmt:
    name: "Rust Fmt"
    runs-on: ubuntu-latest

    steps:
    - name: "Fetch Sources"
      uses: actions/checkout@v3
    - name: "Run rust-fmt"
      run: cargo fmt --verbose -- --check

  rust-clippy:
    name: "Rust Clippy"
    runs-on: ubuntu-latest

    steps:
    - name: "Fetch Sources"
      uses: actions/checkout@v3
    - name: "Run rust-clippy"
      run: cargo clippy --verbose
